/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupColor } from './groupColor';


/**
 * Schema for updating a group.
 */
export interface GroupUpdate { 
    name?: string | null;
    color?: GroupColor | null;
}
export namespace GroupUpdate {
}


