/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupColor } from './groupColor';


/**
 * Schema for creating a new group.
 */
export interface GroupCreate { 
    /**
     * Group name
     */
    name: string;
    color?: GroupColor;
}
export namespace GroupCreate {
}


