/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Predefiniowane kolory dla grup - spójne z paletą UI.
 */
export const GroupColor = {
    Blue: 'blue',
    Green: 'green',
    Red: 'red',
    Yellow: 'yellow',
    Purple: 'purple',
    Pink: 'pink',
    Orange: 'orange',
    Teal: 'teal',
    Indigo: 'indigo',
    Gray: 'gray'
} as const;
export type GroupColor = typeof GroupColor[keyof typeof GroupColor];

