/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupColor } from './groupColor';


/**
 * Schema for group API responses.
 */
export interface Group { 
    /**
     * Group name
     */
    name: string;
    color?: GroupColor;
    id: number;
    userId: number;
    createdAt: string;
    updatedAt: string;
}
export namespace Group {
}


