/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for password reset with token.
 */
export interface PasswordReset { 
    token: string;
    /**
     * Password must be at least 8 characters
     */
    new_password: string;
}

