/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for creating a new todo.
 */
export interface TodoCreate { 
    /**
     * Title must not be empty
     */
    title: string;
    description?: string | null;
    completed?: boolean;
    is_public?: boolean;
}

