/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for updating an existing todo (all fields optional).
 */
export interface TodoUpdate { 
    title?: string | null;
    description?: string | null;
    completed?: boolean | null;
    is_public?: boolean | null;
    index?: number | null;
    group_id?: number | null;
}

