/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for todo API responses (includes id and timestamps).
 */
export interface Todo { 
    /**
     * Title must not be empty
     */
    title: string;
    description?: string | null;
    completed?: boolean;
    is_public?: boolean;
    id: number;
    user_id: number;
    owner_email?: string | null;
    created_at: string;
    updated_at: string;
}

