/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Group } from './group';


/**
 * Schema for todo API responses (includes id and timestamps).
 */
export interface Todo { 
    /**
     * Title must not be empty
     */
    title: string;
    description?: string | null;
    completed?: boolean;
    isPublic?: boolean;
    index?: number;
    groupId?: number | null;
    id: number;
    userId: number;
    ownerEmail?: string | null;
    createdAt: string;
    updatedAt: string;
    group?: Group | null;
}

