/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for JWT token response.
 */
export interface Token { 
    accessToken: string;
    refreshToken: string;
    tokenType?: string;
    message?: string | null;
}

