/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for user API responses.
 */
export interface UserResponse { 
    email: string;
    id: number;
    is_active: boolean;
    is_verified: boolean;
    avatar_url?: string | null;
    language: string;
    created_at: string;
    updated_at: string;
}

