/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for user API responses.
 */
export interface UserResponse { 
    email: string;
    id: number;
    isActive: boolean;
    isVerified: boolean;
    avatarUrl?: string | null;
    language: string;
    message?: string | null;
    createdAt: string;
    updatedAt: string;
}

