/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for user registration.
 */
export interface UserCreate { 
    email: string;
    /**
     * Password must be at least 8 characters
     */
    password: string;
}

