"""initial_schema_camel_case

Revision ID: 658f4b511d04
Revises:
Create Date: 2026-02-19 19:15:32.909673

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "658f4b511d04"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
