"""add_index_to_todo

Revision ID: 786bdc9d1e12
Revises: a1b2c3d4e5f6
Create Date: 2026-02-07 15:21:01.313828

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_index_to_todo

Revision ID: 786bdc9d1e12
Revises: a1b2c3d4e5f6
Create Date: 2026-02-07 15:21:01.313828

"""



# revision identifiers, used by Alembic.
revision: str = "786bdc9d1e12"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first to allow population
    op.add_column("todos", sa.Column("index", sa.Integer(), nullable=True))

    # Initialize index for existing todos
    # We use a raw SQL approach for broad compatibility or a session-based approach
    # For SQLite/Postgres logic:
    # 1. Get all user IDs
    # 2. For each user, get their todos ordered by created_at
    # 3. Update each todo with a sequential index

    connection = op.get_bind()
    # Fetch user_ids who have todos
    user_ids = connection.execute(
        sa.text("SELECT DISTINCT user_id FROM todos")
    ).fetchall()

    for user_id_row in user_ids:
        user_id = user_id_row[0]
        # Fetch todos for this user ordered by created_at
        todos = connection.execute(
            sa.text(
                "SELECT id FROM todos WHERE user_id = :user_id ORDER BY created_at ASC"
            ),
            {"user_id": user_id},
        ).fetchall()

        for idx, todo_row in enumerate(todos):
            todo_id = todo_row[0]
            connection.execute(
                sa.text('UPDATE todos SET "index" = :idx WHERE id = :id'),
                {"idx": idx, "id": todo_id},
            )

    # Now make it non-nullable (Alembic handles this well even for SQLite with batch mode implementation if needed,
    # but for simple SQLite it might require table recreation.
    # Let's try simple nullable=False and see if it works or use batch)
    with op.batch_alter_table("todos") as batch_op:
        batch_op.alter_column("index", nullable=False, server_default="0")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "index")
    # ### end Alembic commands ###
